/* ============================================================
   TEMA GLOBAL — CSS-IN-JS
   Paleta dark industrial com acentos neon
   ============================================================ */
export const theme = {
  colors: {
    bg: '#0a0a0f',
    bgCard: '#14141e',
    bgDark: '#0d0d14',
    border: '#2a2a3e',
    borderGlow: '#4a4a6e',
    text: '#e8e8f0',
    textMuted: '#8888a0',
    textDim: '#5a5a70',
    accent: '#00f0ff',
    accentDim: '#0099aa',
    danger: '#ff3355',
    dangerDim: '#991133',
    success: '#33ff77',
    successDim: '#119944',
    warning: '#ffaa33',
    warningDim: '#996611',
    gold: '#ffd700',
    goldDim: '#aa8800',
    purple: '#aa44ff',
    purpleDim: '#6622aa',
    healthBar: '#ff3355',
    manaBar: '#00bbff',
    xpBar: '#ffd700',
  },
  fonts: {
    primary: "'Courier New', 'Consolas', monospace",
    heading: "'Courier New', 'Consolas', monospace",
  },
  shadows: {
    glow: (color = '#00f0ff') => `0 0 20px ${color}44, 0 0 40px ${color}22`,
    card: '0 4px 24px rgba(0,0,0,0.4)',
  },
  borderRadius: '12px',
  transitions: 'all 0.3s ease',
};

export const gameConfig = {
  MAX_GROUPS: 10,
  PLAYERS_PER_GROUP: '3-5',
  INITIAL_HP: 100,
  INITIAL_MANA: 100,
  INITIAL_XP: 0,
  XP_PER_LEVEL: 100,
  STANDARD_DAMAGE: 8,
  ARTISTIC_DAMAGE: 35,
  ARTISTIC_COST: 20,
  MANA_REGEN: 3,
  AUTO_ADVANCE_DELAY: 3000,
};

export const waves = [
  {
    id: 1,
    name: 'Monstro do Desmatamento',
    title: 'Troncos Carbonizados',
    inspiration: 'Frans Krajcberg',
    emoji: '🌳🔥',
    hp: 500,
    xpReward: 30,
    goldReward: 50,
    itemPool: ['Lata de Tinta Eco', 'Machado de Galho Seco', 'Escudo de Folha'],
    description: 'Criatura feita de troncos queimados e cinzas. Inspirada no engajamento ecológico de Frans Krajcberg contra a destruição das florestas.',
    color: '#ff6633',
  },
  {
    id: 2,
    name: 'Titã do Relógio de Gelo',
    title: 'Derretimento Polar',
    inspiration: 'Olafur Eliasson',
    emoji: '🧊⏰',
    hp: 800,
    xpReward: 50,
    goldReward: 80,
    itemPool: ['Cristal de Gelo Eterno', 'Manto Térmico', 'Poção do Degelo'],
    description: 'Gigante de gelo que derrete lentamente enquanto o tempo corre. Inspirado nas instalações climáticas de Olafur Eliasson.',
    color: '#00ccff',
  },
  {
    id: 3,
    name: 'Criatura Industrial',
    title: 'Lixo Eletrônico e Vigilância',
    inspiration: 'HA Schult & Ai Weiwei',
    emoji: '🤖📸',
    hp: 1200,
    xpReward: 75,
    goldReward: 120,
    itemPool: ['Câmera Quebrada', 'Armadura de Sucata', 'Coração de Robô'],
    description: 'Monte de lixo tecnológico com centenas de câmeras. Fusão das críticas de HA Schult ao consumismo e Ai Weiwei à vigilância estatal.',
    color: '#aa44ff',
  },
  {
    id: 4,
    name: 'Guardião das Arpilleras',
    title: 'Tecido da Resistência',
    inspiration: 'Arpilleras Chilenas',
    emoji: '🧵✊',
    hp: 1800,
    xpReward: 120,
    goldReward: 200,
    itemPool: ['Agulha da Liberdade', 'Manto Bordado', 'Retalho da Memória'],
    description: 'Guardião feito de retalhos de tecido bordados com histórias de luta. Inspirado nas arpilleras chilenas como forma de protesto e memória.',
    color: '#ffd700',
  },
];
